trigger:
  - master

jobs:
  - job: testAndBuild
    container: maven:3-jdk-13
    pool:
      vmImage: 'ubuntu-latest'
    steps:    
      - script: printenv && java --version        
      - task: Maven@3
        displayName: 'mvn compile'
        inputs:
           goals: 'compile'
           options: '-P ssb-bip -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode'
