trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
  - job: testAndBuild
    container: maven@sha256:6d837359937c7aa0449e1dab864bb5c69c7cac896da8776d9c90fd25ed41ea12 # maven:3.6.3-openjdk-15
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
      MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)' 
    steps:  

      #Cache maven artifacts  
      - task: Cache@2
        displayName: Cache Maven local repo
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)

      #Authenticate with maven
      - task: MavenAuthenticate@0
        displayName: 'Authenticate'
        inputs:
          mavenServiceConnections: 'mvnSsbBipPublic, mvnSsbBipReleases, mvnSsbBipSnapshots'

      #Build
      - task: Maven@3
        displayName: 'Compile'
        inputs:
           goals: 'compile'
           options: '-P ssb-bip -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode'
           mavenOptions: '$(MAVEN_OPTS)'

      #Run tests
      - task: Maven@3
        displayName: 'Test'
        inputs:
           goals: 'verify test'
           options: '-P ssb-bip --batch-mode'
           mavenOptions: '$(MAVEN_OPTS)'

      #Deploy artifact upon creating a tag
      - task: Maven@3
        displayName: 'Publish'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
        inputs:
           goals: 'clean deploy'
           options: '-P ssb-bip -DskipTests=true --batch-mode'
           mavenOptions: '$(MAVEN_OPTS)'
