trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
  - job: testAndBuild
    container: maven:3-jdk-13
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
      MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)' 
    steps:  

      #Cache maven artifacts  
      - task: Cache@2
        displayName: Cache Maven local repo
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)
      
      #Build
      - task: Maven@3
        displayName: 'Compile'
        inputs:
           goals: 'compile'
           options: '-p ssb-bip -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode'
           mavenOptions: '$(MAVEN_OPTS)'
      
      #Run tests
      - task: Maven@3
        displayName: 'Test'
        inputs:
           goals: 'verify test'
           options: '-p ssb-bip --batch-mode'
           mavenOptions: '$(MAVEN_OPTS)'
      
      #Deploy artifact upon creating a tag
      - task: Maven@3
        displayName: 'Publish'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
        inputs:
           goals: 'clean deploy'
           options: '-p ssb-bip -DskipTests=true --batch-mode'
           mavenOptions: '$(MAVEN_OPTS)'
